services:
    redis:
        image: redis:6.2
        ports: 
            - "6379:6379"
        volumes: 
            - ./redis_data:/data
        command: "redis-server --appendonly yes"
    
    code:
        image: python:3.9-slim
        volumes: 
            - ./:/root
        environment:
            REDIS_HOST: "redis"
            REDIS_PORT: "6379"